Import Java.util.jar.Attributes.Name;
/** 
 * The HelloWorldApp class implements an application that
 * simply prints "Hello World!" to standard output.
 */
public class HelloWorldApp {
    public static void main(String[] args) {
        String n1 = "Kamusta "; // declare a value of String
        String n2 = "Mundo!"; // declare a value of String
        System.out.println(n1 + n2); // Display the string.
    }
}